/**
 * ServiceErrorKeys is an enum that contains the error codes for the Service layer
 */
export enum ServiceErrorKeys {
    ERROR_PACKAGE_JSON_EXISTS = 'ERROR_PACKAGE_JSON_EXISTS',
    ERROR_TS_CONFIG_EXISTS = 'ERROR_TS_CONFIG_EXISTS',
    ERROR_ESLINT_EXISTS = 'ERROR_ESLINT_EXISTS',
    ERROR_JEST_EXISTS = 'ERROR_JEST_EXISTS',
    ERROR_NPM_IGNORE_EXISTS = 'ERROR_NPM_IGNORE_EXISTS',
    ERROR_ANDESITE_YML_EXISTS = 'ERROR_ANDESITE_YML_EXISTS',
    ERROR_ENTRY_POINT_EXISTS = 'ERROR_ENTRY_POINT_EXISTS',
    ERROR_CREATE_FOLDER_STRUCTURE = 'ERROR_CREATE_FOLDER_STRUCTURE',
    CREATE_FOLDER_STRUCTURE_ERROR = 'CREATE_FOLDER_STRUCTURE_ERROR',
    ERROR_WRITE_FILE = 'ERROR_WRITE_FILE',
    ERROR_ANDESITE_YML_NOT_EXISTS = 'ERROR_ANDESITE_YML_NOT_EXISTS',
    ERROR_TS_CONFIG_NOT_EXISTS = 'ERROR_TS_CONFIG_NOT_EXISTS',
    ERROR_CANCEL_PROMPT = 'ERROR_CANCEL_PROMPT',
 }
 