import { DATABASE_KEY_ERROR } from '#/error/key/databaseKeyError';

/**
 * MSSQL error codes with their corresponding error key.
 */
export const MSSQL_ERROR_CODE: Record<number, typeof DATABASE_KEY_ERROR[keyof typeof DATABASE_KEY_ERROR]> = {
    0: DATABASE_KEY_ERROR.MSSQL_QUERY_ERROR,
    4060: DATABASE_KEY_ERROR.MSSQL_DATABASE_ACCESS_DENIED,
    18452: DATABASE_KEY_ERROR.MSSQL_DATABASE_AUTHORIZATION_FAILED,
    18456: DATABASE_KEY_ERROR.MSSQL_DATABASE_AUTHORIZATION_FAILED,
    102: DATABASE_KEY_ERROR.MSSQL_DATABASE_SYNTAX_ERROR,
    207: DATABASE_KEY_ERROR.MSSQL_DATABASE_COLUMN_NOT_FOUND,
    208: DATABASE_KEY_ERROR.MSSQL_TABLE_NOT_FOUND,
    209: DATABASE_KEY_ERROR.MSSQL_DATABASE_AMBIGUOUS_COLUMN,
    2627: DATABASE_KEY_ERROR.MSSQL_DATABASE_DUPLICATE_KEY,
    547: DATABASE_KEY_ERROR.MSSQL_DATABASE_FOREIGN_KEY_VIOLATION,
    2601: DATABASE_KEY_ERROR.MSSQL_DATABASE_UNIQUE_CONSTRAINT_VIOLATION,
    1205: DATABASE_KEY_ERROR.MSSQL_DATABASE_DEADLOCK_DETECTED,
    1222: DATABASE_KEY_ERROR.MSSQL_DATABASE_RESOURCE_LOCKED,
    3928: DATABASE_KEY_ERROR.MSSQL_DATABASE_TRANSACTION_ABORTED,
    701: DATABASE_KEY_ERROR.MSSQL_DATABASE_INSUFFICIENT_MEMORY,
    1105: DATABASE_KEY_ERROR.MSSQL_DATABASE_INSUFFICIENT_STORAGE,
    8645: DATABASE_KEY_ERROR.MSSQL_DATABASE_QUERY_TIMEOUT,
    9002: DATABASE_KEY_ERROR.MSSQL_DATABASE_TRANSACTION_LOG_FULL,
    8152: DATABASE_KEY_ERROR.MSSQL_DATABASE_DATA_TOO_LARGE,
    229: DATABASE_KEY_ERROR.MSSQL_DATABASE_PERMISSION_DENIED,
    544: DATABASE_KEY_ERROR.MSSQL_DATABASE_IDENTITY_INSERT_NOT_ALLOWED,
    8102: DATABASE_KEY_ERROR.MSSQL_DATABASE_CANNOT_UPDATE_IDENTITY_COLUMN,
} as const;