export const databaseErrorKeys = {
	mssqlConnectionError: 'core.error.mssql.database.connection_error',
	mssqlDisconnectError: 'core.error.mssql.database.disconnect_error',
	mssqlNotConnected: 'core.error.mssql.database.not_connected',
	mssqlNoResult: 'core.error.mssql.database.no_result',
	mssqlQueryError: 'core.error.mssql.database.query_error',
	mssqlDatabaseAccessDenied: 'core.error.mssql.database.access_denied',
	mssqlDatabaseAuthorizationFailed: 'core.error.mssql.database.authorization_failed',
	mssqlDatabaseSyntaxError: 'core.error.mssql.database.syntax_error',
	mssqlDatabaseColumnNotFound: 'core.error.mssql.database.column_not_found',
	mssqlTableNotFound: 'core.error.mssql.database.table_not_found',
	mssqlDatabaseAmbiguousColumn: 'core.error.mssql.database.ambiguous_column',
	mssqlDatabaseDuplicateKey: 'core.error.mssql.database.duplicate_key',
	mssqlDatabaseForeignKeyViolation: 'core.error.mssql.database.foreign_key_violation',
	mssqlDatabaseUniqueConstraintViolation: 'core.error.mssql.database.unique_constraint_violation',
	mssqlDatabaseDeadlockDetected: 'core.error.mssql.database.deadlock_detected',
	mssqlDatabaseResourceLocked: 'core.error.mssql.database.resource_locked',
	mssqlDatabaseTransactionAborted: 'core.error.mssql.database.transaction_aborted',
	mssqlDatabaseInsufficientMemory: 'core.error.mssql.database.insufficient_memory',
	mssqlDatabaseInsufficientStorage: 'core.error.mssql.database.insufficient_storage',
	mssqlDatabaseQueryTimeout: 'core.error.mssql.database.query_timeout',
	mssqlDatabaseTransactionLogFull: 'core.error.mssql.database.transaction_log_full',
	mssqlDatabaseDataTooLarge: 'core.error.mssql.database.data_too_large',
	mssqlDatabasePermissionDenied: 'core.error.mssql.database.permission_denied',
	mssqlDatabaseIdentityInsertNotAllowed: 'core.error.mssql.database.identity_insert_not_allowed',
	mssqlDatabaseCannotUpdateIdentityColumn: 'core.error.mssql.database.cannot_update_identity_column',
	mssqlDatabaseConversionFailed: 'core.error.mssql.database.conversion_failed'
} as const;
