export const DATABASE_ERROR_KEYS = {
	MSSQL_CONNECTION_ERROR: 'mssql.error.database.connection_error',
	MSSQL_DATABASE_ACCESS_DENIED: 'mssql.error.database.access_denied',
	MSSQL_DATABASE_AMBIGUOUS_COLUMN: 'mssql.error.database.ambiguous_column',
	MSSQL_DATABASE_AUTHORIZATION8FAILED: 'mssql.error.database.authorization_failed',
	MSSQL_DATABASE_COLUMN_NOT_FOUND: 'mssql.error.database.column_not_found',
	MSSQL_DATABASE_CONVERSION_FAILED: 'mssql.error.database.conversion_failed',
	MSSQL_DATABASE_DATA_TOO_LARGE: 'mssql.error.database.data_too_large',
	MSSQL_DATABASE_DEADLOCK_DETECTED: 'mssql.error.database.deadlock_detected',
	MSSQL_DATABASE_DUPLICATE_KEY: 'mssql.error.database.duplicate_key',
	MSSQL_DATABASE_FOREIGN_KEY_VIOLATION: 'mssql.error.database.foreign_key_violation',
	MSSQL_DATABASE_IDENTITY_INSERT_NOT_ALLOWED: 'mssql.error.database.identity_insert_not_allowed',
	MSSQL_DATABASE_INSUFFICIENT_MEMORY: 'mssql.error.database.insufficient_memory',
	MSSQL_DATABASE_INSUFFICIENT_STORAGE: 'mssql.error.database.insufficient_storage',
	MSSQL_DATABASE_PERMISSION_DENIED: 'mssql.error.database.permission_denied',
	MSSQL_DATABASE_QUERY_TIMEOUT: 'mssql.error.database.query_timeout',
	MSSQL_DATABASE_RESOURCE_LOCKED: 'mssql.error.database.resource_locked',
	MSSQL_DATABASE_SYNTAX_ERROR: 'mssql.error.database.syntax_error',
	MSSQL_DATABASE_TRANSACTION_ABORTED: 'mssql.error.database.transaction_aborted',
	MSSQL_DATABASE_TRANSACTION_LOG_FULL: 'mssql.error.database.transaction_log_full',
	MSSQL_DATABASE_UNIQUE_CONSTRAINT_VIOLATION: 'mssql.error.database.unique_constraint_violation',
	MSSQL_DATABSE_CANNOT_UPDATE_IDENTITY_COLUMN: 'mssql.error.database.cannot_update_identity_column',
	MSSQL_DISCONNECT_ERROR: 'mssql.error.database.disconnect_error',
	MSSQL_NO_RESULT: 'mssql.error.database.no_result',
	MSSQL_NOT_CONNECTED: 'mssql.error.database.not_connected',
	MSSQL_QUERY_ERROR: 'mssql.error.database.query_error',
	MSSQL_TABLE_NOT_FOUND: 'mssql.error.database.table_not_found'
} as const;
