import { DATABASE_ERROR_KEYS } from './databaseErrorKeys';

export const MSSQL_ERROR_CODE = {
	0: DATABASE_ERROR_KEYS.MSSQL_QUERY_ERROR,
	4060: DATABASE_ERROR_KEYS.MSSQL_DATABASE_ACCESS_DENIED,
	18452: DATABASE_ERROR_KEYS.MSSQL_DATABASE_AUTHORIZATION8FAILED,
	18456: DATABASE_ERROR_KEYS.MSSQL_DATABASE_AUTHORIZATION8FAILED,
	102: DATABASE_ERROR_KEYS.MSSQL_DATABASE_SYNTAX_ERROR,
	207: DATABASE_ERROR_KEYS.MSSQL_DATABASE_COLUMN_NOT_FOUND,
	208: DATABASE_ERROR_KEYS.MSSQL_TABLE_NOT_FOUND,
	209: DATABASE_ERROR_KEYS.MSSQL_DATABASE_AMBIGUOUS_COLUMN,
	2627: DATABASE_ERROR_KEYS.MSSQL_DATABASE_DUPLICATE_KEY,
	547: DATABASE_ERROR_KEYS.MSSQL_DATABASE_FOREIGN_KEY_VIOLATION,
	2601: DATABASE_ERROR_KEYS.MSSQL_DATABASE_UNIQUE_CONSTRAINT_VIOLATION,
	1205: DATABASE_ERROR_KEYS.MSSQL_DATABASE_DEADLOCK_DETECTED,
	1222: DATABASE_ERROR_KEYS.MSSQL_DATABASE_RESOURCE_LOCKED,
	3928: DATABASE_ERROR_KEYS.MSSQL_DATABASE_TRANSACTION_ABORTED,
	701: DATABASE_ERROR_KEYS.MSSQL_DATABASE_INSUFFICIENT_MEMORY,
	1105: DATABASE_ERROR_KEYS.MSSQL_DATABASE_INSUFFICIENT_STORAGE,
	8645: DATABASE_ERROR_KEYS.MSSQL_DATABASE_QUERY_TIMEOUT,
	9002: DATABASE_ERROR_KEYS.MSSQL_DATABASE_TRANSACTION_LOG_FULL,
	8152: DATABASE_ERROR_KEYS.MSSQL_DATABASE_DATA_TOO_LARGE,
	229: DATABASE_ERROR_KEYS.MSSQL_DATABASE_PERMISSION_DENIED,
	544: DATABASE_ERROR_KEYS.MSSQL_DATABASE_IDENTITY_INSERT_NOT_ALLOWED,
	8102: DATABASE_ERROR_KEYS.MSSQL_DATABSE_CANNOT_UPDATE_IDENTITY_COLUMN,
	8169: DATABASE_ERROR_KEYS.MSSQL_DATABASE_CONVERSION_FAILED
} as const;