name: job-integration-test
run-name: "[job-integration-test] ${{ inputs.branch }}"

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        type: string
    secrets:
      BUN_VERSION:
        required: false
      KEY_SSH:
        required: true
      MSSQL_HOST:
        required: true
      MSSQL_DATABASE:
        required: true
      MSSQL_USER:
        required: true
      MSSQL_PASSWORD:
        required: true

jobs:
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      MSSQL_HOST: ${{ secrets.MSSQL_HOST }}
      MSSQL_DATABASE: ${{ secrets.MSSQL_DATABASE }}
      MSSQL_USER: ${{ secrets.MSSQL_USER }}
      MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          ssh-key: ${{ secrets.KEY_SSH }}

      - name: Setup Bun Project
        uses: ./.github/actions/setup-bun-project
        with:
          bun-version: ${{ secrets.BUN_VERSION || 'latest' }}

      - name: Run Integration Tests
        run: bun run test:integration