name: job-build
run-name: "[job-build] ${{ inputs.branch }}"

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        type: string
    secrets:
      KEY_SSH:
        required: true

env:
  BUN_VERSION: 1.2.23

jobs:
  check-build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Verify required secrets
        run: |
          echo "🔍 Verifying required secrets for build job..."
          if [ -z "${{ secrets.KEY_SSH }}" ]; then
            echo "❌ KEY_SSH secret is missing"
            exit 1
          fi
          echo "✅ All required secrets are present"

      - name: Setup Project Environment
        uses: ./.github/actions/setup
        with:
          branch: ${{ inputs.branch }}
          ssh-key: ${{ secrets.KEY_SSH }}
          bun-version: ${{ env.BUN_VERSION }}

      - name: Run Build
        run: bun run build
