name: job-integration-test
run-name: "[job-integration-test] ${{ inputs.branch }}"

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        type: string
    secrets:
      KEY_SSH:
        required: true
      MSSQL_HOST:
        required: true
      MSSQL_DATABASE:
        required: true
      MSSQL_USER:
        required: true
      MSSQL_PASSWORD:
        required: true

env:
  BUN_VERSION: 1.2.23

jobs:
  run-integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      MSSQL_HOST: ${{ secrets.MSSQL_HOST }}
      MSSQL_DATABASE: ${{ secrets.MSSQL_DATABASE }}
      MSSQL_USER: ${{ secrets.MSSQL_USER }}
      MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
    steps:
      - name: Verify required secrets
        run: |
          echo "🔍 Verifying required secrets for integration test job..."
          for secret in KEY_SSH MSSQL_HOST MSSQL_DATABASE MSSQL_USER MSSQL_PASSWORD; do
            if [ -z "$(eval echo \$\{$secret\})" ]; then
              echo "❌ $secret secret is missing"
              exit 1
            fi
          done
          echo "✅ All required secrets are present"
        env:
          KEY_SSH: ${{ secrets.KEY_SSH }}
          MSSQL_HOST: ${{ secrets.MSSQL_HOST }}
          MSSQL_DATABASE: ${{ secrets.MSSQL_DATABASE }}
          MSSQL_USER: ${{ secrets.MSSQL_USER }}
          MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}

      - name: Setup Project Environment
        uses: ./.github/actions/setup
        with:
          branch: ${{ inputs.branch }}
          ssh-key: ${{ secrets.KEY_SSH }}
          bun-version: ${{ env.BUN_VERSION }}

      - name: Run Integration Tests and update Summary
        id: integration_test
        run: bun run test:integration
