name: job-rebase
run-name: "[job-rebase] ${{ inputs.from }} -> ${{ inputs.to }}"

on:
  workflow_call:
    inputs:
      from:
        description: 'Branch to rebase from'
        required: true
        type: string
      to:
        description: 'Branch to rebase to'
        required: true
        type: string
    secrets:
      KEY_SSH:
        required: true
      GIT_EMAIL:
        required: true
  workflow_dispatch:
    inputs:
      from:
        description: 'Branch to rebase from'
        required: true
        type: string
      to:
        description: 'Branch to rebase to'
        required: true
        type: string

env:
  BUN_VERSION: 1.2.23

jobs:
  rebase-branches:
    name: Rebase Branches
    runs-on: ubuntu-latest
    steps:
      - name: Verify required secrets
        run: |
          echo "🔍 Verifying required secrets for rebase job..."
          for secret in KEY_SSH GIT_EMAIL; do
            if [ -z "$(eval echo \$\{$secret\})" ]; then
              echo "❌ $secret secret is missing"
              exit 1
            fi
          done
          echo "✅ All required secrets are present"
        env:
          KEY_SSH: ${{ secrets.KEY_SSH }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

      - name: Setup Project Environment
        uses: ./.github/actions/setup
        with:
          branch: ${{ inputs.from }}
          ssh-key: ${{ secrets.KEY_SSH }}
          bun-version: ${{ env.BUN_VERSION }}
          install-deps: 'false'

      - name: Fetch all branches
        run: git fetch origin '+refs/heads/*:refs/remotes/origin/*'

      - name: Rebase
        run: |
          git config user.name "GitHub Action"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git checkout ${{ inputs.from }}
          git rebase origin/${{ inputs.to }}
          git push origin ${{ inputs.from }}
